//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.uksusoff.rock63;

import android.content.Context;
import android.content.SharedPreferences;
import com.googlecode.androidannotations.api.sharedpreferences.EditorHelper;
import com.googlecode.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefEditorField;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefField;

public final class ISharedPrefs_
    extends SharedPreferencesHelper
{


    public ISharedPrefs_(Context context) {
        super(context.getSharedPreferences("ISharedPrefs", 0));
    }

    public ISharedPrefs_.ISharedPrefsEditor_ edit() {
        return new ISharedPrefs_.ISharedPrefsEditor_(getSharedPreferences());
    }

    public StringPrefField theme() {
        return stringField("theme", "dark");
    }

    public final static class ISharedPrefsEditor_
        extends EditorHelper<ISharedPrefs_.ISharedPrefsEditor_>
    {


        ISharedPrefsEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public StringPrefEditorField<ISharedPrefs_.ISharedPrefsEditor_> theme() {
            return stringField("theme");
        }

    }

}
