//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.uksusoff.rock63;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.SeekBar;
import android.widget.TextView;
import com.uksusoff.rock63.R.layout;

public final class RadioPlayerView_
    extends RadioPlayerView
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        playBtn = ((ImageButton) findViewById(com.uksusoff.rock63.R.id.radio_play_btn));
        trackTitle = ((TextView) findViewById(com.uksusoff.rock63.R.id.radio_track_title));
        volumeBar = ((SeekBar) findViewById(com.uksusoff.rock63.R.id.radio_volume_bar));
        init();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.radio_fragment, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static RadioPlayerView_.FragmentBuilder_ builder() {
        return new RadioPlayerView_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public RadioPlayerView build() {
            RadioPlayerView_ fragment_ = new RadioPlayerView_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
